esp_toml_version = 1.0
firmware_images_url = "https://shubhamdp.github.io/esp_ota/esp32s3_test_devices/"

supported_apps = ["ESP32S3_Device_1"]

[ESP32S3_Device_1]
chipsets = ["ESP32S3"]
image.esp32 = "esp32s3_device1.bin"
