esp_toml_version = 1.0
firmware_images_url = "https://espressif.github.io/esp-matter/"

supported_apps = ["light","light_switch"]

[light]
chipsets = ["ESP32","ESP32C3"]
image.esp32 = "esp32_light.bin"
image.esp32c3 = "esp32c3_light.bin"
ios_app_url = "https://apps.apple.com/in/app/espressif-matter/id1604739172"
android_app_url = ""

[light_switch]
chipsets = ["ESP32","ESP32C3"]
image.esp32 = "esp32_light_switch.bin"
image.esp32c3 = "esp32c3_light_switch.bin"
ios_app_url = "https://apps.apple.com/in/app/espressif-matter/id1604739172"
android_app_url = ""
