esp_toml_version = 1.0
firmware_images_url = "https://espressif.github.io/esp-matter/"

supported_apps = ["light","light_switch"]
setup_payload_logo = "https://upload.wikimedia.org/wikipedia/commons/f/fd/Matter_logo.jpg"
setup_payload = "MT:Y.K9042C00KA0648G00"

[light]
chipsets = ["ESP32","ESP32C3","ESP32C6","ESP32H2"]
image.esp32 = "esp32_light.bin"
image.esp32c3 = "esp32c3_light.bin"
image.esp32c6 = "esp32c6_light.bin"
image.esp32h2 = "esp32h2_light.bin"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"
android_app_url = ""

[light_switch]
chipsets = ["ESP32","ESP32C3","ESP32C6","ESP32H2"]
image.esp32 = "esp32_light_switch.bin"
image.esp32c3 = "esp32c3_light_switch.bin"
image.esp32c6 = "esp32c6_light_switch.bin"
image.esp32h2 = "esp32h2_light_switch.bin"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"
android_app_url = ""
