esp_toml_version = 1.0
firmware_images_url = "https://shubhamdp.github.io/esp_ota/internal_test_dev/"

supported_apps = ["C3_First_Light", "C3_Second_Light", "C3_Third_Light", "C3_Fourth_Light", "C3_Fifth_Light"]

[C3_First_Light]
chipsets = ["ESP32C3"]
image.esp32c3 = "mss_test_device1.bin"

[C3_Second_Light]
chipsets = ["ESP32C3"]
image.esp32c3 = "mss_test_device2.bin"

[C3_Third_Light]
chipsets = ["ESP32C3"]
image.esp32c3 = "mss_test_device3.bin"

[C3_Fourth_Light]
chipsets = ["ESP32C3"]
image.esp32c3 = "mss_test_device4.bin"

[C3_Fifth_Light]
chipsets = ["ESP32C3"]
image.esp32c3 = "mss_test_device5.bin"
