esp_toml_version = 1.0
firmware_images_url = "https://shubhamdp.github.io/esp_ota/test_devices/"

supported_apps = ["ESP32C3_Device_1"]

[ESP32C3_Device_1]
chipsets = ["ESP32C3"]
image.esp32c3 = "esp32c3_device1.bin"
